name: "Build and push image on native architecture"

# run workflow on every branch, only upload on main (allow manual trigger)
on:
  # build image on push
  push:
    # don't build if only docs changed
    paths-ignore:
      - "**.md"

  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Enable SSH access at the end of the workflow"
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: "Build packages"

    #runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            rust_target: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            rust_target: aarch64-unknown-linux-gnu

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@v4
      - uses: arduino/setup-protoc@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.rust_target }}

      - name: Clone ankitects/anki repository
        uses: actions/checkout@v4
        with:
          repository: ankitects/anki
          path: ankitects-anki
          submodules: true

      #- name: Setup interactive ssh session
      #  uses: Warpbuilds/action-debugger@v1.3

      - name: Generate fake artifacts
        run: |
          echo "Moin ${{ matrix.rust_target }}" > ${{ github.workspace }}/ankitects-anki/target/${{ matrix.rust_target }}/release/anki-sync-server

      #- name: Build anki-sync-server with release profile
      #  run: |
      #    cd ${{ github.workspace }}/ankitects-anki/
      #    PROTOC=$(which protoc) \
      #    RUSTFLAGS='-C target-feature=+crt-static' \
      #    cargo build --release --target ${{ matrix.rust_target }} --package anki-sync-server

      - name: Upload binary to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: anki-sync-server-${{ matrix.rust_target }}
          path: ${{ github.workspace }}/ankitects-anki/target/${{ matrix.rust_target }}/release/anki-sync-server
          if-no-files-found: error

  build-and-push-image:
    name: "Build and push Docker image"

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Download binary for x86_64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: anki-sync-server-x86_64-unknown-linux-gnu
          path: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/anki-sync-server

      - name: Download binary for aarch64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: anki-sync-server-aarch64-unknown-linux-gnu
          path: ${{ github.workspace }}/target/aarch64-unknown-linux-gnu/anki-sync-server

      - name: Setup interactive ssh session
        uses: Warpbuilds/action-debugger@v1.3
